<a href="https://colab.research.google.com/github/RojaCM/DEEP-LEARNING-/blob/main/text%20calssification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from torch.utils.data import TensorDataset
from tqdm.notebook import tqdm
import numpy as np

#Multi Class Text Classification With Deep Learning Using BERT | by Susan Li | Towards Data Science

In [ ]:
data=pd.read_csv('sample_dex_data.csv')

In [ ]:
df=data.copy()

In [ ]:
df.head()

,Unnamed: 0,title,summary,category
0,0,Reminder - Optimus - Best People Manager 2022,Today is the last day for voting (14th October...,TWEETS
1,1,"It starts this 23 October, till 26 October 202...",Hope you are all set to attend Money 2020 USA ...,TWEETS
2,2,Congratulations Triveni Arun Bhalerao | Long S...,NaN,WHO_SAID_WHAT
3,3,Long Service Awards - 5 years - Triveni Arun ...,NaN,STORY_OF_THE_DAY
4,4,tweets testing,today testing preview screen and toast success...,TWEETS

In [ ]:
df1=df[['title','category']]

In [ ]:
df1.head()

                                               title          category
0     Reminder - Optimus -  Best People Manager 2022            TWEETS
1  It starts this 23 October, till 26 October 202...            TWEETS
2  Congratulations Triveni Arun Bhalerao | Long S...     WHO_SAID_WHAT
3   Long Service Awards - 5 years - Triveni Arun ...  STORY_OF_THE_DAY
4                                     tweets testing            TWEETS

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting transformers
  Downloading transformers-4.23.1-py3-none-any.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 35.4 MB/s
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from transformers) (21.3)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Downloading tokenizers-0.13.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.6 MB)
     |████████████████████████████████| 7.6 MB 57.5 MB/s
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.7/dist-packages (from transformers) (4.64.1)
Collecting huggingface-hub<1.0,>=0.10.0
  Downloading huggingface_hub-0.10.1-py3-none-any.whl (163 kB)
     |████████████████████████████████| 163 kB 75.2 MB/s
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (1.21.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (2022.6.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers) (3.8.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.7/dist-packages (from transformers) (6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from transformers) (2.23.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers) (4.13.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from huggingface-hub<1.0,>=0.10.0->transformers) (4.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->transformers) (3.0.9)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers) (3.9.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2022.9.24)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2.10)
Installing collected packages: tokenizers, huggingface-hub, transformers
Successfully installed huggingface-hub-0.10.1 tokenizers-0.13.1 transformers-4.23.1

In [ ]:
import torch
from transformers import BertTokenizer
from transformers import  BertForSequenceClassification

In [ ]:
df1['category'].value_counts()

TWEETS                      246
COMPANY_INFORMATION         171
STORY_OF_THE_DAY            105
TECHNO_PICKS                 92
INDUSTRY_UPDATE              87
WHO_SAID_WHAT                65
FEATURED_VIDEOS              53
SUCCESS_STORY                33
PEOPLE_OF_ALTIMETRIK         27
ALTIMETRIK_NEWS              26
EMPLOYEE_EXPERIENCES         22
ABOUT_ALTIMETRIK             19
CAPABILITY_CENTERS           13
GLOBAL_RECOGNITIONS          12
INNOVATION_AT_ALTIMETRIK     11
TRENDING_STORY                7
EBOOK                         6
STATIC_CONTENT                4
DIGITAL_BUSINESS              1
Name: category, dtype: int64

In [ ]:
df1['category'].unique()

array(['TWEETS', 'WHO_SAID_WHAT', 'STORY_OF_THE_DAY',
       'COMPANY_INFORMATION', 'SUCCESS_STORY', 'FEATURED_VIDEOS',
       'TECHNO_PICKS', 'INDUSTRY_UPDATE', 'CAPABILITY_CENTERS',
       'TRENDING_STORY', 'INNOVATION_AT_ALTIMETRIK',
       'GLOBAL_RECOGNITIONS', 'ABOUT_ALTIMETRIK', 'DIGITAL_BUSINESS',
       'PEOPLE_OF_ALTIMETRIK', 'EMPLOYEE_EXPERIENCES', 'ALTIMETRIK_NEWS',
       'STATIC_CONTENT', 'EBOOK'], dtype=object)

In [ ]:
#encoding the categories
possible_labels = df1.category.unique()

label_dict = {}
for index, possible_label in enumerate(possible_labels):
    label_dict[possible_label] = index
label_dict

{'TWEETS': 0,
 'WHO_SAID_WHAT': 1,
 'STORY_OF_THE_DAY': 2,
 'COMPANY_INFORMATION': 3,
 'SUCCESS_STORY': 4,
 'FEATURED_VIDEOS': 5,
 'TECHNO_PICKS': 6,
 'INDUSTRY_UPDATE': 7,
 'CAPABILITY_CENTERS': 8,
 'TRENDING_STORY': 9,
 'INNOVATION_AT_ALTIMETRIK': 10,
 'GLOBAL_RECOGNITIONS': 11,
 'ABOUT_ALTIMETRIK': 12,
 'DIGITAL_BUSINESS': 13,
 'PEOPLE_OF_ALTIMETRIK': 14,
 'EMPLOYEE_EXPERIENCES': 15,
 'ALTIMETRIK_NEWS': 16,
 'STATIC_CONTENT': 17,
 'EBOOK': 18}

In [ ]:
df1['label']=df1['category'].replace(label_dict)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df1

,title,category,label
0,Reminder - Optimus - Best People Manager 2022,TWEETS,0
1,"It starts this 23 October, till 26 October 202...",TWEETS,0
2,Congratulations Triveni Arun Bhalerao | Long S...,WHO_SAID_WHAT,1
3,Long Service Awards - 5 years - Triveni Arun ...,STORY_OF_THE_DAY,2
4,tweets testing,TWEETS,0
...,...,...,...
995,"Employee Referral Virtual Drive - 14 May, 2022",COMPANY_INFORMATION,3
996,The Future Trends In Mobility And Transportation,INDUSTRY_UPDATE,7
997,The Keys to Pricing Power as Recession Looms,INDUSTRY_UPDATE,7
998,Intelligence and unified data governance in th...,TECHNO_PICKS,6
999,Creating a defined data centric space with AI ...,TECHNO_PICKS,6

In [ ]:
df1['label'].value_counts()

0     246
3     171
2     105
6      92
7      87
1      65
5      53
4      33
14     27
16     26
15     22
12     19
8      13
11     12
10     11
9       7
18      6
17      4
13      1
Name: label, dtype: int64

In [ ]:
df2=df1.copy()

In [ ]:
df1[df1['label']==13]

                  title          category  label
437  Digital Business 2  DIGITAL_BUSINESS     13

In [ ]:
df1.drop(437,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df1['label'].value_counts()

0     246
3     171
2     105
6      92
7      87
1      65
5      53
4      33
14     27
16     26
15     22
12     19
8      13
11     12
10     11
9       7
18      6
17      4
Name: label, dtype: int64

Train and Validation Split
Because the labels are imbalanced, we split the data set in a stratified fashion, using this as the class labels.

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(df1.index.values, 
                                                  df1.label.values, 
                                                  test_size=0.3, 
                                                  random_state=42, 
                                                  stratify=df1.label.values)

In [ ]:
df1.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 438, 439, 440, 441, 442,
       443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455,
       456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468,
       469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481,
       482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494,
       495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507,
       508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520,
       521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533,
       534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546,
       547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559,
       560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572,
       573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585,
       586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598,
       599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611,
       612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624,
       625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637,
       638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650,
       651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663,
       664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676,
       677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689,
       690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702,
       703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715,
       716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728,
       729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741,
       742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754,
       755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767,
       768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780,
       781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793,
       794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806,
       807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819,
       820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832,
       833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845,
       846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858,
       859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871,
       872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884,
       885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897,
       898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910,
       911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923,
       924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936,
       937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949,
       950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962,
       963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975,
       976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988,
       989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [ ]:
df1['data_type'] = ['not_set']*df1.shape[0]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df1

,title,category,label,data_type
0,Reminder - Optimus - Best People Manager 2022,TWEETS,0,not_set
1,"It starts this 23 October, till 26 October 202...",TWEETS,0,not_set
2,Congratulations Triveni Arun Bhalerao | Long S...,WHO_SAID_WHAT,1,not_set
3,Long Service Awards - 5 years - Triveni Arun ...,STORY_OF_THE_DAY,2,not_set
4,tweets testing,TWEETS,0,not_set
...,...,...,...,...
995,"Employee Referral Virtual Drive - 14 May, 2022",COMPANY_INFORMATION,3,not_set
996,The Future Trends In Mobility And Transportation,INDUSTRY_UPDATE,7,not_set
997,The Keys to Pricing Power as Recession Looms,INDUSTRY_UPDATE,7,not_set
998,Intelligence and unified data governance in th...,TECHNO_PICKS,6,not_set
999,Creating a defined data centric space with AI ...,TECHNO_PICKS,6,not_set

In [ ]:
df1.loc[X_train, 'data_type'] = 'train'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [ ]:
df1

,title,category,label,data_type
0,Reminder - Optimus - Best People Manager 2022,TWEETS,0,train
1,"It starts this 23 October, till 26 October 202...",TWEETS,0,not_set
2,Congratulations Triveni Arun Bhalerao | Long S...,WHO_SAID_WHAT,1,not_set
3,Long Service Awards - 5 years - Triveni Arun ...,STORY_OF_THE_DAY,2,train
4,tweets testing,TWEETS,0,train
...,...,...,...,...
995,"Employee Referral Virtual Drive - 14 May, 2022",COMPANY_INFORMATION,3,train
996,The Future Trends In Mobility And Transportation,INDUSTRY_UPDATE,7,train
997,The Keys to Pricing Power as Recession Looms,INDUSTRY_UPDATE,7,train
998,Intelligence and unified data governance in th...,TECHNO_PICKS,6,train
999,Creating a defined data centric space with AI ...,TECHNO_PICKS,6,not_set

In [ ]:
df1.loc[X_val, 'data_type'] = 'val'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [ ]:
df1

,title,category,label,data_type
0,Reminder - Optimus - Best People Manager 2022,TWEETS,0,train
1,"It starts this 23 October, till 26 October 202...",TWEETS,0,val
2,Congratulations Triveni Arun Bhalerao | Long S...,WHO_SAID_WHAT,1,val
3,Long Service Awards - 5 years - Triveni Arun ...,STORY_OF_THE_DAY,2,train
4,tweets testing,TWEETS,0,train
...,...,...,...,...
995,"Employee Referral Virtual Drive - 14 May, 2022",COMPANY_INFORMATION,3,train
996,The Future Trends In Mobility And Transportation,INDUSTRY_UPDATE,7,train
997,The Keys to Pricing Power as Recession Looms,INDUSTRY_UPDATE,7,train
998,Intelligence and unified data governance in th...,TECHNO_PICKS,6,train
999,Creating a defined data centric space with AI ...,TECHNO_PICKS,6,val

In [ ]:
df1.groupby(['category','label','data_type']).count()

                                          title
category                 label data_type
ABOUT_ALTIMETRIK         12    train         13
                               val            6
ALTIMETRIK_NEWS          16    train         18
                               val            8
CAPABILITY_CENTERS       8     train          9
                               val            4
COMPANY_INFORMATION      3     train        120
                               val           51
EBOOK                    18    train          4
                               val            2
EMPLOYEE_EXPERIENCES     15    train         15
                               val            7
FEATURED_VIDEOS          5     train         37
                               val           16
GLOBAL_RECOGNITIONS      11    train          8
                               val            4
INDUSTRY_UPDATE          7     train         61
                               val           26
INNOVATION_AT_ALTIMETRIK 10    train          8
                               val            3
PEOPLE_OF_ALTIMETRIK     14    train         13
                               val            7
STATIC_CONTENT           17    train          3
                               val            1
STORY_OF_THE_DAY         2     train         74
                               val           31
SUCCESS_STORY            4     train         23
                               val           10
TECHNO_PICKS             6     train         64
                               val           28
TRENDING_STORY           9     train          5
                               val            2
TWEETS                   0     train        172
                               val           74
WHO_SAID_WHAT            1     train         46
                               val           19

In [ ]:
list(df1['title'])
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 999 entries, 0 to 999
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      992 non-null    object
 1   category   999 non-null    object
 2   label      999 non-null    int64
 3   data_type  999 non-null    object
dtypes: int64(1), object(3)
memory usage: 71.3+ KB

BertTokenizer and Encoding the Data

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', 
                                          do_lower_case=True)
                                          
encoded_data_train = tokenizer.batch_encode_plus(
   list(df1[df1.data_type=='train'].title.values), 
    add_special_tokens=True, 
    return_attention_mask=True, 
    pad_to_max_length=True, 
    max_length=256,
    return_tensors='pt'
)

encoded_data_val = tokenizer.batch_encode_plus(
    list(df1[df1.data_type=='train'].title.values), 
    add_special_tokens=True, 
    return_attention_mask=True, 
    pad_to_max_length=True, 
    max_length=256,
    return_tensors='pt'
)


input_ids_train = encoded_data_train['input_ids']
attention_masks_train = encoded_data_train['attention_mask']
labels_train = torch.tensor(df1[df1.data_type=='train'].label.values)

input_ids_val = encoded_data_val['input_ids']
attention_masks_val = encoded_data_val['attention_mask']
labels_val = torch.tensor(df1[df1.data_type=='val'].label.values)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.

ValueError: ignored

In [ ]:
dataset_train = TensorDataset(input_ids_train, attention_masks_train, labels_train)
dataset_val = TensorDataset(input_ids_val, attention_masks_val, labels_val)

NameError: ignored

BERT Pre-trained Model

In [ ]:
model = BertForSequenceClassification.from_pretrained("bert-base-uncased",
                                                      num_labels=len(label_dict),
                                                      output_attentions=False,
                                                      output_hidden_states=False)

Downloading:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler

batch_size = 3

dataloader_train = DataLoader(dataset_train, 
                              sampler=RandomSampler(dataset_train), 
                              batch_size=batch_size)

dataloader_validation = DataLoader(dataset_val, 
                                   sampler=SequentialSampler(dataset_val), 
                                   batch_size=batch_size)

NameError: ignored

Optimizer & Scheduler

In [ ]:
from transformers import AdamW, get_linear_schedule_with_warmup

optimizer = AdamW(model.parameters(),
                  lr=1e-5, 
                  eps=1e-8)
                  
epochs = 5

scheduler = get_linear_schedule_with_warmup(optimizer, 
                                            num_warmup_steps=0,
                                            num_training_steps=len(dataloader_train)*epochs)

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,

NameError: ignored

#Performance Metrics
We will use f1 score and accuracy per class as performance metrics.

In [ ]:
from sklearn.metrics import f1_score

def f1_score_func(preds, labels):
    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return f1_score(labels_flat, preds_flat, average='weighted')

def accuracy_per_class(preds, labels):
    label_dict_inverse = {v: k for k, v in label_dict.items()}
    
    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()

    for label in np.unique(labels_flat):
        y_preds = preds_flat[labels_flat==label]
        y_true = labels_flat[labels_flat==label]
        print(f'Class: {label_dict_inverse[label]}')
        print(f'Accuracy: {len(y_preds[y_preds==label])}/{len(y_true)}\n')

Training Loop

In [ ]:
import random

seed_val = 17
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

def evaluate(dataloader_val):

    model.eval()
    
    loss_val_total = 0
    predictions, true_vals = [], []
    
    for batch in dataloader_val:
        
        batch = tuple(b.to(device) for b in batch)
        
        inputs = {'input_ids':      batch[0],
                  'attention_mask': batch[1],
                  'labels':         batch[2],
                 }

        with torch.no_grad():        
            outputs = model(**inputs)
            
        loss = outputs[0]
        logits = outputs[1]
        loss_val_total += loss.item()

        logits = logits.detach().cpu().numpy()
        label_ids = inputs['labels'].cpu().numpy()
        predictions.append(logits)
        true_vals.append(label_ids)
    
    loss_val_avg = loss_val_total/len(dataloader_val) 
    
    predictions = np.concatenate(predictions, axis=0)
    true_vals = np.concatenate(true_vals, axis=0)
            
    return loss_val_avg, predictions, true_vals
    
for epoch in tqdm(range(1, epochs+1)):
    
    model.train()
    
    loss_train_total = 0

    progress_bar = tqdm(dataloader_train, desc='Epoch {:1d}'.format(epoch), leave=False, disable=False)
    for batch in progress_bar:

        model.zero_grad()
        
        batch = tuple(b.to(device) for b in batch)
        
        inputs = {'input_ids':      batch[0],
                  'attention_mask': batch[1],
                  'labels':         batch[2],
                 }       

        outputs = model(**inputs)
        
        loss = outputs[0]
        loss_train_total += loss.item()
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        optimizer.step()
        scheduler.step()
        
        progress_bar.set_postfix({'training_loss': '{:.3f}'.format(loss.item()/len(batch))})
         
        
    torch.save(model.state_dict(), f'data_volume/finetuned_BERT_epoch_{epoch}.model')
        
    tqdm.write(f'\nEpoch {epoch}')
    
    loss_train_avg = loss_train_total/len(dataloader_train)            
    tqdm.write(f'Training loss: {loss_train_avg}')
    
    val_loss, predictions, true_vals = evaluate(dataloader_validation)
    val_f1 = f1_score_func(predictions, true_vals)
    tqdm.write(f'Validation loss: {val_loss}')
    tqdm.write(f'F1 Score (Weighted): {val_f1}')

NameError: ignored